### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by peet-hex** [pepstock-org/Charba-Showcase#1]
This is probably a silly configuration problem.
Cloned and compiled Charba with ant
Cloned Charba-Showcase, imported in Eclipse, added charba-2.0.jar as external jar.
Now trying to compile with GWT 2.8.1

Get the following errors:
Compiling module org.pepstock.charba.showcase.Charba_Showcase
   Tracing compile failure path for type 'org.pepstock.charba.client.data.Dataset'
      [ERROR] Errors in 'jar:file:/home/peet/eclipse-workspace/Charba/dist/charba-2.0.jar!/org/pepstock/charba/client/data/Dataset.java'
         [ERROR] Line 54: No source code is available for type java.util.concurrent.atomic.AtomicInteger; did you forget to inherit a required module?
   Tracing compile failure path for type 'org.pepstock.charba.client.plugins.AbstractPluginOptions'
      [ERROR] Errors in 'jar:file:/home/peet/eclipse-workspace/Charba/dist/charba-2.0.jar!/org/pepstock/charba/client/plugins/AbstractPluginOptions.java'
         [ERROR] Line 35: No source code is available for type java.util.concurrent.atomic.AtomicInteger; did you forget to inherit a required module?
   Tracing compile failure path for type 'org.pepstock.charba.client.colors.CanvasObject'
      [ERROR] Errors in 'jar:file:/home/peet/eclipse-workspace/Charba/dist/charba-2.0.jar!/org/pepstock/charba/client/colors/CanvasObject.java'
         [ERROR] Line 33: No source code is available for type java.util.concurrent.atomic.AtomicInteger; did you forget to inherit a required module?
   [ERROR] Aborting compile due to errors in some input files

**Comment by stockiNail** [comment]
@peet-hex  we are providing Charba based on GWT2.8.2. Checking the source code of GWT, AtomicInteger is provided by [Oct 2017](https://github.com/gwtproject/gwt/commits/f031aba1e5aff65143005de841a491b42fe1031a/user/super/com/google/gwt/emul/java/util/concurrent/atomic/AtomicInteger.java), after version 2.8.1 and for 2.8.2

**Comment by peet-hex** [comment]
Thanks , that did it!
